apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: narmesteleder-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /arbeidgsgiver/ansatte/narmesteleder/api/internal/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /arbeidgsgiver/ansatte/narmesteleder/api/internal/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - 'https://www.ekstern.dev.nav.no/arbeidgsgiver/ansatte/narmesteleder'
