apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: {{appname}}-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
    branchState: {{branchState}}
spec:
  image: {{image}}
  ttl: {{ ttl }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  tokenx:
    enabled: false
  idporten:
    enabled: false
    sidecar:
      enabled: false
  liveness:
    path: /arbeidgsgiver/ansatte/narmesteleder/api/internal/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /arbeidgsgiver/ansatte/narmesteleder/api/internal/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - {{ingress}}
  env:
    - name: NARMESTELEDER_BACKEND_URL
      value: http://esyfo-narmesteleder
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker